export const ActionTypes = {
  GET_NEWS_POSTS: 'GET_NEWS_POSTS',
  UPDATE_NEWS_POSTS: 'UPDATE_NEWS_POSTS',
  GET_TOP_NEWS_POSTS: 'GET_TOP_NEWS_POSTS',
  UPDATE_TOP_NEWS_POSTS: 'UPDATE_TOP_NEWS_POSTS',
  GET_NEWS_TAGS: 'GET_NEWS_TAGS',
  UPDATE_NEWS_TAGS: 'UPDATE_NEWS_TAGS',
  SET_SORT_TYPE: 'SET_SORT_TYPE',
  SET_FILTERS: 'SET_FILTERS',
  SET_POSTS_LIMITED: 'SET_LIMITED',

  GET_INDIVIDUAL_NEWS_POST: 'GET_INDIVIDUAL_NEWS_POST',
  UPDATE_INDIVIDUAL_NEWS_POST: 'UPDATE_INDIVIDUAL_NEWS_POST'
}
